apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  selector:
    matchLabels:
      app: mongo
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
      - name: config
        configMap:
          name: "mongo-init" 
      - name: vdata
        hostPath:
          path: /vdata 
      containers:
      - name: mongo
        image: mongo:4.2.23
        command: 
        - bash
        - /config/init.sh
        volumeMounts:
        - name: config
          mountPath: /config 
        - name: mongodb-scripts
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
        - name: vdata
          mountPath: /data/db       
          subPathExpr: $(POD_NAME)
        resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
        env:
        - name: mongodb-scripts
          configMap:
            name: mongodb-create-user
            items:
            - key: ensure-users.js
              path: ensure-users.js
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: pass
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name    
        ports:
        - containerPort:  27017
          protocol: TCP
        #livenessProbe:
        #  exec:
        #    command:
        #    - mongo
        #    - --eval
        #    - db.serverStatus()
        #  initialDelaySeconds: 180
        #  timeoutSeconds: 60 
  #volumeClaimTemplates:
  #- metadata:
  #    name: mongo-volume
  #  spec:
  #    accessModes: [ "ReadWriteOnce" ]
  #    resources:
  #      requests:
  #        storage: 1Gi