apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  selector:
    matchLabels:
      app: mongo
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
    spec:
      volumes:
      - name: vdata
        hostPath:
          path: /vdata 
      containers:
      - name: mongo
        image: mongo:4.2.23
        command: 
        - mongod 
        - "--bind_ip_all"
        - "--replSet"
        - rs0
        volumeMounts:
        - name: config
          mountPath: /config 
        - name: vdata
          mountPath: /data/db       
          subPathExpr: $(POD_NAME)
        resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: pass
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name    
        ports:
        - containerPort:  27017
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - db.serverStatus()
          initialDelaySeconds: 180
          timeoutSeconds: 60 