apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-create-user
data:
  #mongo.conf: |
  #  storage:
  #    dbPath: /data/db
  ensure-users.js: |
    // Create user
    dbAdmin = db.getSiblingDB("admin");
    dbAdmin.createUser({
      user: "customerUser",
      pwd: "password",
      roles: [{ role: "userAdminAnyDatabase", db: "admin" }],
      mechanisms: ["SCRAM-SHA-1"],
    });

    // Authenticate user
    dbAdmin.auth({
      user: "adminUser",
      pwd: "password",
      mechanisms: ["SCRAM-SHA-1"],
      digestPassword: true,
    });