apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - headless-service.yaml
  - mongo-svc-0.yaml
  - mongo-svc-1.yaml
  - mongo-svc-2.yaml
  - mongodb-statefulset-config-less.yaml