apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
      - name: vdata
        hostPath:
          path: /vdata 
      containers:
      - name: mongo
        image: mongo
        command: 
        - mongod 
        - "--bind_ip_all"
        - "--replSet"
        - rs0
        ports:
        - containerPort: 27017
        env:
        #- name: MONGO_INITDB_ROOT_USERNAME
        #  valueFrom:
        #      secretKeyRef:
        #        name: mongo-secret
        #        key: user
        #- name: MONGO_INITDB_ROOT_PASSWORD
        #  valueFrom:
        #      secretKeyRef:
        #        name: mongo-secret
        #        key: pass
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name  
        volumeMounts:
        - name: vdata
          mountPath: /data/db 
          subPathExpr: $(POD_NAME)

